### ISSUE TITLE
Compiler error: vector is not a template

### ISSUE THREAD

**Issue by vra** [liruoteng/FlowNet#11] opened 2017-04-06 06:27 UTC
Hi @liruoteng ,
When I compile this project, I encouter error message below, which like `/usr/local/include/opencv2/gpu/gpu.hpp(438): error: vector is not a template`. I searched the issues of this project and caffe, but not find similar question. Can you give me some adivices? Thanks.

### System info
Distro: Ubuntu 14.04
OpenCV: 3.1.0
CUDA: 8.0
CuDNN: v5

### Error message
```bash
/usr/local/include/opencv2/gpu/gpu.hpp(438): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1265): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1266): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1267): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1285): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1287): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1288): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1289): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1291): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1295): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1300): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1301): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1301): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1303): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1305): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1835): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1836): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1838): error: vector is not a template

/usr/local/include/opencv2/gpu/gpu.hpp(1839): error: vector is not a template

20 errors detected in the compilation of "/tmp/user/1005/tmpxft_0000045e_00000000-19_resample_layer.compute_61.cpp1.ii".
```

**Comment by liruoteng** [comment] 2017-04-08 12:04
Hi I am not very sure about the cause. but are you able to successfully compile original caffe?

Ruoteng

**Comment by vra** [comment] 2017-04-08 15:20
Hi @liruoteng ,
Thanks for your response.  Following your advice, I found that the errors appear when compiling the file `src/caffe/layers/resample_layer.cu`， in which the opencv head files are included but not used. So I comment them and the make  process passed! Thanks again!
So I create a [PR](https://github.com/liruoteng/FlowNet/pull/12) to this repo, hope that helps.

**Comment by liruoteng** [comment] 2017-04-10 02:48
Thank you very much for your information! Yea, some of the .cpp/.cu files are written only in this project and they are compatible with specific opencv version. So if everything is going on well with original caffe, then usually they are the cause of compiler issue. 

I will close this issue for now. 

Thanks
Ruoteng

**Closed as completed by liruoteng** 2017-04-10 02:48 UTC
